os: linux

language: minimal

addons:
  apt:
    packages:
      - docker-ce

before_script:
  - docker pull hadolint/hadolint
  - docker-compose pull

script:
  - docker run --rm -i hadolint/hadolint < $(git ls-files --exclude='Dockerfile*' --ignored)
  - docker-compose build
  - >
    docker-compose \
      -f docker-compose.yaml \
      -f docker-compose.dev.yaml \
      build

notifications:
  webhooks:
    urls:
      - https://fathomless-fjord-24024.herokuapp.com/notify
    on_success: change
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always
  email: false
