os: linux

addons:
  apt:
    packages:
      - docker-ce

script:
  - docker --version
  - docker-compose up --build --exit-code-from bot --abort-on-container-exit

notifications:
  webhooks:
    urls:
      - https://fathomless-fjord-24024.herokuapp.com/notify
    on_success: change
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always
  email: false
