os: linux

language: minimal

addons:
  apt:
    packages:
      - docker-ce

script:
  - docker-compose build bot

notifications:
  webhooks:
    urls:
      - https://fathomless-fjord-24024.herokuapp.com/notify
    on_success: change
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always
  email: false
