version: '3.7'

services:
  bot:
    build:
      dockerfile: Dockerfile.dev
      target: debugger
    ports:
      - "40000:40000"
    security_opt:
      - apparmor=unconfined
    cap_add:
      - SYS_PTRACE
