version: '3.7'

networks:
  telego:

volumes:
  go_modules:
  clickhouse:

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
      args:
        _project_path: "github.com/mitinarseny/telego"
        GID: 12345
        UID: 54321
    environment:
      TELEGO_LOG_DB_HOST: log_db
      TELEGO_LOG_DB_PORT: 27017
      TELEGO_LOG_DB_USER: bot
      TELEGO_LOG_DB_PASSWORD: Password123!
      TELEGO_LOG_DB_NAME: log
      TELEGO_ADMIN_DB_NAME: administration
    depends_on:
      - log_db
    networks:
      - telego

  log_db:
    image: mongo:4.2.0-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: bot
      MONGO_INITDB_ROOT_PASSWORD: Password123!
    ports:
      - 27017:27017
    networks:
      - telego
