version: '3.7'

networks:
  telego:

services:
  bot:
    build:
      context: .
      target: server
      args:
        _project_path: "github.com/mitinarseny/telego"
        _path: "."
    networks:
      - telego
