version: '3.7'

networks:
  telego:

volumes:
  clickhouse:

services:
  bot:
    build:
      context: .
      target: server
      args:
        _project_path: "github.com/mitinarseny/telego"
        GID: 12345
        UID: 54321
    environment:
      - TELEGO_LOG_DB_HOST=log_db
      - TELEGO_LOG_DB_PORT=9000
      - TELEGO_LOG_DB_USER=logger
      - TELEGO_LOG_DB_PASSWORD=password123
#      - TELEGO_LOG_DB_NAME=updates
    restart: on-failure
    networks:
      - telego

  log_db:
    image: yandex/clickhouse-server
    volumes:
      - "./clickhouse/config/:/etc/clickhouse-server/:ro"
      - "./clickhouse/entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:ro"
      - "clickhouse:/var/lib/clickhouse"
    restart: on-failure
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost/"]
#      interval: 1m
#      timeout: 10s
#      retries: 3
#      start_period: 30s
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 8123:8123
    networks:
      - telego
